### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by arashkhoeini** [wjmaddox/swa_gaussian#13]
I believe it would be nice if you could easily choose whether you want to run the code on CPU or GPU. My understanding is that all related parameters are hard-coded now.

**Comment by wjmaddox** [comment]
Yes, you're correct that [run_swag](https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/train/run_swag.py) is hard-coded to use a gpu if it's found. however, you should be able to easily add a command line arg to use cuda only if desired in that script.

**Comment by wjmaddox** [comment]
Should be resolved by #12
