### ISSUE TITLE
Replicating results of transfer learning and out-of-domain image detection

### ISSUE THREAD

**Issue by amitchandak** [wjmaddox/swa_gaussian#14]
Hi,
Can you please share some details about how can I replicate results of these experiments ? 
How can I generate files used in "out_of_dist_plots.ipynb" which is present in "unceratinity" folder in experiments sections ? 

Thank You

**Comment by wjmaddox** [comment]
Sure, first, you'll have to train models as described in the [README here](https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/train/README.md). Then, using a saved checkpoint, you can compute the uncertainties overall in this [README](https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/uncertainty/README.md). Running those scripts will save .npz files of all predictions. 

For all of those models, we trained using the first half of the CIFAR classes, which is the `--split_classes=0` flag throughout; that is, you'll have to add that flag into whatever training and evaluation scripts you use.

Hope this helps,

**Comment by amitchandak** [comment]
Hi,
Thanks for your reply and apologies for very late reply.
I tried to replicate transfer learning experiment. The models were trained as you mentioned [here](https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/train/README.md) and then predictions were done on STL-10 dataset. 

**Example Command:** 
python3.6 ./experiments/uncertainty/uncertainty.py  --data_path=<stl_dataPath> --dataset=STL10 --model=VGG16 --use_test --cov_mat --method=SWAG --scale=0.5 --file=<vgg16_swagModelPath> --save_path=<save_path>

**Results:** (Averaged over three runs with different random seed)

**NLL Results:** 
|Model | VGG-16 | PreResNet-164  | WideResNet28x10|
|---------|-------------|-----------------------|--------------------------|
|SWAG(Reported)| 1.1402 ± 0.0342 |0.9706 ± 0.00 |0.8710 ± 0.00| 
|SWAG(Reproduced)| 0.8565 ± 0.0007|0.7783±0.0141 |0.66± 0.0013|

**Accuracy Results**
|Model | VGG-16 | PreResNet-164  | WideResNet28x10|
|---------|-------------|-----------------------|--------------------------|
|SWAG(Reported)| 72.19 ± 0.06 |75.88 ± 0.00 |77.09 ± 0.00| 
|SWAG(Reproduced)| 72.30 ±0.12 |75.836±0.16 |76.86± 0.07|

I have used **exact** parameter values to train the models as mentioned so not sure why NLL numbers are different than once mentioned in paper. Can you please give some feedback on this ?

Thanks,
Amit

**Comment by wjmaddox** [comment]
Hmm... so those are all numbers that are pretty similar to what we are reporting and in all but accuracy on WRN, slightly _better_ than the numbers we reported (lower NLL is better, higher accuracy is better). I'm pretty confident that this is just random seeds (don't know what @izmailovpavel used 18 mos ago) and/or slight changes in pytorch since we last ran the experiments.
