### ISSUE TITLE
Could you share the pretrained model for imagenet?

### ISSUE THREAD

**Issue by xztema0207** [wjmaddox/swa_gaussian#17]
I hope to research your proposal, SWGA for imagenet. 
Could you share the pretrained model for imagenet?

**Comment by wjmaddox** [comment]
Hi,

We used pre-trained models, which can be downloaded from https://pytorch.org/docs/stable/torchvision/models.html following our code. 

However, we haven't published the SWAG checkpoints at the end of training due to their size --- @timgaripov might be able to provide them if he still has them.

**Comment by Haijunlv** [comment]
@wjmaddox  could you  release the training scripts for imagenet? like lr config, ..  
so that we can repulicate the result in the paper

**Comment by Haijunlv** [comment]
using python  experiments/imagenet/run_swag_imagenet.py  
     --batch_size=256 \
    --pretrained \
    --parallel \
    --epochs=10 \
    --save_freq=10 \
    --eval_freq=1 \
    --swa \
    --swa_start=0 \
    --swa_lr=0.001 \
    --swa_freq=4 
can republicate the result

**Comment by wjmaddox** [comment]
That sounds about right given the hyper-parameters in Appendix H of https://arxiv.org/pdf/1902.02476.pdf
