### ISSUE TITLE
Loading SWAG Checkpoint and Continue SWAG Training

### ISSUE THREAD

**Issue by FloLins** [wjmaddox/swa_gaussian#23]
Dear SWAG Team,

I am currently using your SWAG Code for my own Research and stumbled upon the following problem:

Continuing SGD Training from a Checkpoint is not a problem.
How I start the code:
python3 experiments/train/run_swag.py --data_path=<PATH> --epochs=300 --dataset=CIFAR100 --save_freq=10 --model=VGG16 --lr_init=0.05 --wd=5e-4 --swa --swa_start=161 --swa_lr=0.01 --cov_mat --use_test --dir=<PATH> --resume=<CHACKPOINT PATH>

But I am not able to continue SWAG Training. I found the parameter "saw_resume", but I am not able to get the code running.
How I start the code:
python3 experiments/train/run_swag.py --data_path=<PATH> --epochs=300 --dataset=CIFAR100 --save_freq=10 --model=VGG16 --lr_init=0.05 --wd=5e-4 --swa --swa_start=161 --swa_lr=0.01 --cov_mat --use_test --dir=<PATH> --swa_resume=<SWAG CHACKPOINT PATH>

I get the following Error Message, when the Code tries to initialize the SWAG Object:
  File "PATH/swa_gaussian-master/experiments/train/run_swag.py", line 252, in <module>
    swag_model = SWAG(
  File "PATH/swa_gaussian-master/swag/posteriors/swag.py", line 49, in __init__
    self.base = base(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'loading'

How can I get this running?

Thanks for your help,
Yours sincerely,
Florian Linsner

**Comment by wjmaddox** [comment]
Can you just remove that flag in the code?

**Comment by FloLins** [comment]
Thanks for your reply.
What do you mean by removing the flag?
Didn't I need the "swa_resume" flag to load and continue SWAG Training.?

**Comment by FloLins** [comment]
Thanks for your reply.
I changed the code to:
    swag_model = SWAG(
        model_cfg.base,
        no_cov_mat=args.no_cov_mat,
        max_num_models=args.max_num_models,
        #loading=True, #Now the Flag is removed
        *model_cfg.args,
        num_classes=num_classes,
        **model_cfg.kwargs
    )
   
   This does omit the error, but the training just started from epoch one and the SWAG checkpoint is not loaded.
   Loading a non SWAG training Checkpoint is still possible.

**Comment by izmailovpavel** [comment]
Hey @FloLins so I think in order to actually resume training, you need to also load the non-swag checkpoint with the `resume` flag: https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/train/run_swag.py#L243-L248 this part loads the optimizer and the base model parameters. Do you have a regular checkpoint or just the SWAG one?

**Comment by FloLins** [comment]
Hey @izmailovpavel I already tried that.
In your paper you use 300 epochs of training. (160 till local minima and 140 SWAG training)
I loaded the normal checkpoint from 160 and from 200 and observed the accuracy and final results.
The run loaded from 160 has a higher accuracy as the run loaded from 200.
It seems that the algorithm just starts SWAG training from beginning instead of loading SWAG parameters and continuing SWAG training.

Does this load the SWAG Parameters too?
https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/train/run_swag.py#L243-L248

**Comment by izmailovpavel** [comment]
Hey @FloLins you have to use both `resume` and `swa_resume` to load both the base model / optimizer and the swag model. Sorry for the confusion.

**Comment by FloLins** [comment]
Hey @izmailovpavel I tried that too before opening this issue, and it didn't work due to the "loading=True" flag
If I comment this flag out (line 261 in run_swag.py) like @wjmaddox suggested and use both parameters "resume" and "swa_resume" it works fine!

Will any other functionality broke down, if I keep this flag commented out?


Thanks for all your help and have a nice day,

Yours sincerely,
Florian Linsner

**Comment by izmailovpavel** [comment]
Hi @FloLins, glad that it worked! 

I think you could even completely remove these lines: https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/train/run_swag.py#L252-L260.

I don't remember why we had the `loading` parameter, but I don't think it's used anywhere.
