### ISSUE TITLE
'CIFAR10' object has no attribute 'targets'

### ISSUE THREAD

**Issue by jhss** [wjmaddox/swa_gaussian#9]
I have some error when I run this script

>python3 experiments/train/run_swag.py --data_path=/home/jh/data/ --epochs=300 -->dataset=CIFAR10 --save_freq=300 --model=PreResNet164 --lr_init=0.1 --wd=3e-4 -->swa --swa_start=161 --swa_lr=0.01 --cov_mat --use_test -->dir=/home/jh/swa_gaussian/experiments/train/checkpoint`

I have CUDA 8.0, and install 'python setup.py develop', but I have the following error.

>Preparing directory /home/jh/swa_gaussian/experiments/train/checkpoint
>Using model PreResNet164
>Loading dataset CIFAR10 from /home/jh/data/

>Files already downloaded and verified
>Traceback (most recent call last):
>  File "experiments/train/run_swag.py", line 186, in <module>
>   split_classes=args.split_classes,
>  File "/home/jh/swa_gaussian/swag/data.py", line 196, in loaders
>    num_classes = max(train_set.targets) + 1
> AttributeError: 'CIFAR10' object has no attribute 'targets'

What should I do?

**Comment by jhss** [comment]
I fixed this issue when I change torchvision from 0.2.1 to 0.2.2.

**Comment by surajpaib** [comment]
#11 Fixes this issue
